name: CI
on: [push]

jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    runs-on: ubuntu-latest

    services:
      mysql:
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: trust

        image: mysql:latest

        ports:
          - 3306:3306

    steps:
      - uses: actions/checkout@v2

      - name: Versions
        run: |
          node -v
          google-chrome --version
          chromedriver -v

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)

        with:
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}

          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Yarn install
        run: yarn --frozen-lockfile

      - name: Yarn test
        uses: GabrielBB/xvfb-action@v1.2

        with:
          run: yarn test

      - name: Ruby and Bundle Install
        uses: eregon/use-ruby-action@v1

        with:
          bundler-cache: true

      - name: Database
        run: bundle exec rake db:create db:schema:load

      - name: Spec
        env:
          CAPYBARA_BOX__S3_ACCESS_KEY_ID: ${{ secrets.CAPYBARA_BOX__S3_ACCESS_KEY_ID }}
          CAPYBARA_BOX__S3_SECRET_ACCESS_KEY: ${{ secrets.CAPYBARA_BOX__S3_SECRET_ACCESS_KEY }}
          CI: true
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
          COVERAGE: true
          MINIMUM_COVERAGE: 80
          RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}

        run: bundle exec rspec
